"""Initial Migration

Revision ID: 992acb859d60
Revises: addf54a72a7a
Create Date: 2019-09-28 14:37:24.066862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992acb859d60'
down_revision = 'addf54a72a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
